###
POST  http://127.0.0.1:3000/users/signUp HTTP/1.1
Content-Type: application/json 

{
    "email": "mraidi@test.com",
    "password": "testtest",
    "age": 28,
    "name": "achref",
    "lastName":"mraidi"

}


###
POST  http://127.0.0.1:3000/users/signIn HTTP/1.1
Content-Type: application/json 

{
    "email": "mraidi@test.com",
    "password": "testtest"

}