@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1yYWlkaTNAdGVzdC5jb20iLCJpYXQiOjE3MTEzODI3MzEsImV4cCI6MTcxMTM4Mjc5MX0.BjlDh_Uv9TZzLvX-kVxszrDSYqBYHkoMmaK3bsvUAQE
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1yYWlkaTNAdGVzdC5jb20iLCJpYXQiOjE3MTEzODQxNTEsImV4cCI6MTcxMTM4NTM1MX0.-j5PNitC61Ms_mrrznvSJUAJJE8rPRzLyHtl-cdW-N0

###
POST  http://127.0.0.1:3000/users/signUp HTTP/1.1
Content-Type: application/json 

{
    "email": "ref@test.com",
    "password": "testtest",
    "age": 28,
    "name": "achref",
    "lastName":"mraidi"

}


###
POST  http://127.0.0.1:3000/users/signIn HTTP/1.1
Content-Type: application/json 

{
    "email": "mraidi3@test.com",
    "password": "testtest"

}

###
POST  http://127.0.0.1:3000/users/udpateUser HTTP/1.1
Content-Type: application/json 
Authorization: bearer {{ token  }}

{
    "email": "mraidi44@test.com",
    "password": "testtest",
    "age": 554

}


###
POST  http://127.0.0.1:3000/users/refreshToken HTTP/1.1
Content-Type: application/json 
Authorization: bearer {{ refreshToken  }}

{

}